# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BookZone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookZone
   pod "Alamofire"
   pod 'SWXMLHash', '~> 5.0.0'
   pod 'lottie-ios'
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'GoogleSignIn'

end
