# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'BookZone' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookZone
   pod "Alamofire"
   pod 'SWXMLHash', '~> 5.0.0'
   pod 'lottie-ios'
   pod 'Firebase/Analytics'
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Storage'
   pod 'Firebase/Core'
   pod 'SDWebImage','~>4.4.2'
   pod 'JGProgressHUD','~>2.0.3'
   pod 'FaveButton'
   pod 'EasyTipView', '~> 2.0.4'
   pod 'SwipeCellKit'
   pod 'SwiftyJSON', '~> 4.0'
   pod 'Parchment', '~> 3.0'

end
